version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: slim-fastapi-app
    image: slim-fastapi-app
    command: /app/start.sh
    ports:
      - 8080:8080
    env_file: ../../dev.env
    depends_on:
      - data_base

  data_base:
    image: postgres:12.1-alpine
    container_name: slim-data-base-app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=slim_fast_api
    ports: 
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    container_name: slim-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80
    depends_on:
      - data_base
    
  
volumes:
  postgres_data: