version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: docker-develop.dockerfile
    container_name: fastapi-app-develop-container
    image: fastapi-app-develop-image
    command: cd /app/ && make run
    ports:
      - 8080:8080
    env_file: ../../develop.env
    depends_on:
      - data_base

  data_base:
    image: postgres:12.1-alpine
    container_name: data-base-app-container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fastapi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastapi_pass}
      POSTGRES_DB: ${POSTGRES_DB:-fast_api}
    ports: 
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80
    depends_on:
      - data_base
    
  
volumes:
  postgres_data: